pre-commit:
  parallel: true
  commands:
    formatting:
      glob: "*.nix"
      run: |
        make format FILES="{staged_files}"
        git add {staged_files}

pre-push:
  commands:
    build:
      run: |
        make build