pre-commit:
  parallel: true
  commands:
    nixfmt:
      glob: "*.nix"
      run: |
        make format FILES="{staged_files}"
        git add {staged_files}

pre-push:
  commands:
    ensure-build:
      run: |
        echo "🔨 Running 'make build' to validate configuration before push..."
        make build